import type { Atom, Grid3D } from '../types';

const BOHR_TO_ANG = 0.529177249;
const ANG_TO_BOHR = 1.0 / BOHR_TO_ANG;

const SYMBOLS: Record<number, string> = {
  1: 'H', 2: 'He', 3: 'Li', 4: 'Be', 5: 'B', 6: 'C', 7: 'N', 8: 'O', 9: 'F', 10: 'Ne',
  11: 'Na', 12: 'Mg', 13: 'Al', 14: 'Si', 15: 'P', 16: 'S', 17: 'Cl', 18: 'Ar',
  19: 'K', 20: 'Ca', 26: 'Fe', 29: 'Cu', 30: 'Zn', 35: 'Br', 53: 'I',
};

export interface CubeFileData {
  atoms: Atom[];
  grid: Grid3D;
  scalarField: Float64Array;
}

/**
 * Parse a Gaussian Cube file.
 * Cube format: coordinates in Bohr, data order x-slowest z-fastest.
 * Internal format: coordinates in Angstrom, data order z-slowest x-fastest.
 */
export function parseCubeFile(text: string): CubeFileData {
  const lines = text.split(/\r?\n/);
  let li = 2; // skip 2 comment lines

  // Line 3: NAtoms originX originY originZ
  const line3 = lines[li++].trim().split(/\s+/);
  let nAtoms = parseInt(line3[0]);
  const hasMOHeader = nAtoms < 0;
  nAtoms = Math.abs(nAtoms);
  const ox = parseFloat(line3[1]) * BOHR_TO_ANG;
  const oy = parseFloat(line3[2]) * BOHR_TO_ANG;
  const oz = parseFloat(line3[3]) * BOHR_TO_ANG;

  // Lines 4-6: Ni stepXi stepYi stepZi
  const axes: { n: number; sx: number; sy: number; sz: number }[] = [];
  for (let a = 0; a < 3; a++) {
    const p = lines[li++].trim().split(/\s+/);
    axes.push({
      n: Math.abs(parseInt(p[0])),
      sx: parseFloat(p[1]),
      sy: parseFloat(p[2]),
      sz: parseFloat(p[3]),
    });
  }

  const nx = axes[0].n;
  const ny = axes[1].n;
  const nz = axes[2].n;

  // Spacing (assume orthogonal grid)
  const spacingX = Math.sqrt(axes[0].sx ** 2 + axes[0].sy ** 2 + axes[0].sz ** 2) * BOHR_TO_ANG;
  const spacingY = Math.sqrt(axes[1].sx ** 2 + axes[1].sy ** 2 + axes[1].sz ** 2) * BOHR_TO_ANG;
  const spacingZ = Math.sqrt(axes[2].sx ** 2 + axes[2].sy ** 2 + axes[2].sz ** 2) * BOHR_TO_ANG;
  const spacing = (spacingX + spacingY + spacingZ) / 3;

  // Atoms
  const atoms: Atom[] = [];
  for (let a = 0; a < nAtoms; a++) {
    const p = lines[li++].trim().split(/\s+/);
    const atomicNumber = parseInt(p[0]);
    atoms.push({
      symbol: SYMBOLS[atomicNumber] || 'X',
      index: a + 1,
      atomicNumber,
      position: {
        x: parseFloat(p[2]) * BOHR_TO_ANG,
        y: parseFloat(p[3]) * BOHR_TO_ANG,
        z: parseFloat(p[4]) * BOHR_TO_ANG,
      },
    });
  }

  // Skip MO header if present
  if (hasMOHeader) li++;

  // Read volumetric data values
  const values: number[] = [];
  for (; li < lines.length; li++) {
    const parts = lines[li].trim().split(/\s+/);
    for (const v of parts) {
      if (v !== '') values.push(parseFloat(v));
    }
  }

  // Remap: cube data[ix*ny*nz + iy*nz + iz] → field[iz*ny*nx + iy*nx + ix]
  const field = new Float64Array(nx * ny * nz);
  let ci = 0;
  for (let ix = 0; ix < nx; ix++) {
    for (let iy = 0; iy < ny; iy++) {
      for (let iz = 0; iz < nz; iz++) {
        field[iz * ny * nx + iy * nx + ix] = values[ci++];
      }
    }
  }

  return {
    atoms,
    grid: {
      origin: { x: ox, y: oy, z: oz },
      size: { x: nx, y: ny, z: nz },
      spacing,
    },
    scalarField: field,
  };
}

/**
 * Export scalar field data as a Gaussian Cube file string.
 */
export function exportCubeFile(
  atoms: Atom[],
  grid: Grid3D,
  scalarField: Float64Array,
  comment1 = 'Generated by MOrbVis',
  comment2 = '',
): string {
  const lines: string[] = [];
  const { origin, size, spacing } = grid;
  const nx = size.x, ny = size.y, nz = size.z;
  const sBohr = spacing * ANG_TO_BOHR;

  lines.push(comment1);
  lines.push(comment2);

  // Header
  const fmt = (v: number) => v.toFixed(6).padStart(12);
  lines.push(`${String(atoms.length).padStart(5)} ${fmt(origin.x * ANG_TO_BOHR)} ${fmt(origin.y * ANG_TO_BOHR)} ${fmt(origin.z * ANG_TO_BOHR)}`);
  lines.push(`${String(nx).padStart(5)} ${fmt(sBohr)} ${fmt(0)} ${fmt(0)}`);
  lines.push(`${String(ny).padStart(5)} ${fmt(0)} ${fmt(sBohr)} ${fmt(0)}`);
  lines.push(`${String(nz).padStart(5)} ${fmt(0)} ${fmt(0)} ${fmt(sBohr)}`);

  // Atoms
  for (const atom of atoms) {
    lines.push(
      `${String(atom.atomicNumber).padStart(5)} ${fmt(0)}` +
      ` ${fmt(atom.position.x * ANG_TO_BOHR)}` +
      ` ${fmt(atom.position.y * ANG_TO_BOHR)}` +
      ` ${fmt(atom.position.z * ANG_TO_BOHR)}`
    );
  }

  // Volumetric data: outer x, middle y, inner z, 6 per line
  for (let ix = 0; ix < nx; ix++) {
    for (let iy = 0; iy < ny; iy++) {
      const row: string[] = [];
      for (let iz = 0; iz < nz; iz++) {
        const val = scalarField[iz * ny * nx + iy * nx + ix];
        row.push(val.toExponential(5).padStart(13));
        if (row.length === 6) {
          lines.push(row.join(''));
          row.length = 0;
        }
      }
      if (row.length > 0) lines.push(row.join(''));
    }
  }

  return lines.join('\n');
}
